#!/bin/bash
rsync -rv --exclude-from 'exclude-list.txt' .??* ~
rsync -rv --exclude-from 'exclude-list.txt' README*  ~
rsync -rv --exclude-from 'exclude-list.txt' .git-completion.bash  ~
rsync -rv --exclude-from 'exclude-list.txt' .gitconfig  ~
